# Generated by Django 5.1.3 on 2024-11-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_lowattendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="admin_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="admin",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="attendance_percentage",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="parents_mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="ssc_gpa",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
