# Generated by Django 5.0.1 on 2024-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_student_attendance_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(default="None", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
