# Generated by Django 5.0.7 on 2024-12-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="attendance_date",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject_name",
            field=models.CharField(
                choices=[("present", "Present"), ("absent", "Absent")],
                default="absent",
                max_length=100,
            ),
        ),
    ]
