# Generated by Django 5.1.3 on 2024-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_attendance_date_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject_name",
            field=models.CharField(max_length=100),
        ),
    ]
