# Generated by Django 5.1.3 on 2024-12-09 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_alter_attendance_date_alter_attendance_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="date",
        ),
        migrations.AddField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
